version: '3.3'

services:
  server:
    build: .
    ports:
      - "8080:8080"
    links:
      - mysql:mysql
    restart: always
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: 'json'
      MYSQL_USER: 'kim'
      MYSQL_PASSWORD: 'json'
      MYSQL_DATABASE: 'myDB'
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "52000:3306"